---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service-expose
  namespace: default
  labels:
    app: inventory-service
spec:
  ports:
  - name: inventory-service
    protocol: TCP
    port: 31710
    targetPort: 2222
    nodePort: 31710
  selector:
    app: inventory-service
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  labels:
    app: inventory-service
spec:
  ports:
  - port: 2222
    targetPort: 2222
    name: inventory-service
  clusterIP: None
  selector:
    app: inventory-service
---    
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: inventory-service
spec:
  serviceName: "inventory-service"
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - resources:
          requests:
            cpu: 100m
            memory: 192Mi 
        name: inventory-service
        image: mycluster.icp:8500/default/kbastani/inventory-service:latest
        ports:
        - containerPort: 1111
        env:
        - name: JAVA_OPTS
          value: |
            -Xmx160m
        - name: spring.profiles.active
          value: "cloud"
        - name: spring.cloud.config.uri
          value: "http://config-service.default.svc.cluster.local:8888"
        - name: server.port
          value: "2222"
  podManagementPolicy: "Parallel"